# Generated by Django 4.0 on 2022-01-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0002_file_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='data_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
