# Generated by Django 4.0 on 2022-01-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0003_file_completed_file_data_create_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='products/%s/%s/%s'),
        ),
    ]
