# Generated by Django 4.0 on 2022-01-08 01:24

from django.db import migrations, models
import fileManager.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=fileManager.models.content_file_name),
        ),
    ]
